name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3.2.0
        with:
          node-version: 16
          
      - run: |
          npm install
          
      - run: |
          npm run all
  
      - run: echo "Start action at $(date)"
      
      - uses: ./
        id: me
        with:
          milliseconds: 15000
          
      - run: echo "Time from action ${{ steps.me.outputs.time }}"
