name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.1.1
        with:
          node-version: 16
      - run: |
          npm install
      - run: |
          npm run all
      - name: Create a pull request if files in dist have changed
        uses: peter-evans/create-pull-request@v4
        with:
          path: dist/index.js
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - run: echo "Start action at $(date)"
      - uses: ./
        id: me
        with:
          milliseconds: 15000
      - run: echo "Time from action ${{ steps.me.outputs.time }}"
